### ISSUE TITLE
Some tests are not executed on 1.0.32

### ISSUE THREAD

**Issue by rongi** [mannodermaus/android-junit5#111]
Reproducible on 1.0.32, not reproducible on 1.2.0.0.

1. Use the sample project https://github.com/rongi/junit5bugsampleproject
2. Run ./gradlew testDebugUnitTest from the console

No tests are are executed for the `BetaTestZap` test.

Tests are running ok for the two other classes: `AlphaTest` and `BetaTest`.

Android Studio can see and run all the tests. Changing this to JUnit4 makes it work.

In my real project half of the tests are not executed. Some of them are not executed from Android Studio also.

Test result xmls can be found here: https://github.com/rongi/junit5bugsampleproject/tree/master/test-results/debug/junit-platform

**Comment by mannodermaus** [comment]
Test discovery on the older versions of the plugin used to mirror the same behavior imposed by the (now deprecated) JUnit 5 Gradle plugin. In particular, there is a `ClassNameFilter` in place by default, which looks for test classes matching a certain regular expression. [This is still in the JUnit Platform codebase](https://github.com/junit-team/junit5/blob/7559f13f759ce5e2d754532940ec15934247a623/junit-platform-engine/src/main/java/org/junit/platform/engine/discovery/ClassNameFilter.java#L39), however the latest version of _my_ plugin doesn't use this value anymore. This is why it works for you when upgrading the plugin to `1.2.0.0`. Since your `BetaTestZap` neither starts with `Test`, nor ends with either `Test` or `Tests`, the plugin doesn't discover this class on its own.

In the old DSL, you should be able to manually add another class name filter to the created tasks, so that they recognize your `BetaTestZap` class:

```groovy
// android-junit5 1.0.32 and older
android.testOptions.junitPlatform {
  filters {
    // Default
    includeClassNamePatterns "^(Test.*|.+[.$]Test.*|.*Tests?)$"
    // Test classes ending with "Zap"
    includeClassNamePatterns "^(.*Zap)$"
  }
}
```

In the new DSL, you can register new patterns like so:
```groovy
// android-junit5 1.2.0.0 and later
android.testOptions.junitPlatform {
  filters {
    // Default
    includePattern "^(Test.*|.+[.$]Test.*|.*Tests?)$"
    // Test classes ending with "Zap"
    includePattern "^(.*Zap)$"
  }
}
```

**Comment by rongi** [comment]
Thank you for your answer, it was very useful!
