### ISSUE TITLE
@Nested instrumentation tests aren't wrapped correctly in test report window

### ISSUE THREAD

**Issue by gipsey** [mannodermaus/android-junit5#147]
Hi,

Set up [@Nested](https://junit.org/junit5/docs/current/user-guide/#writing-tests-nested) annotated classes for **instrumentation** tests, however tests in report window are not hierarchized.

Here is an output, after running nested, instrumentation tests:
https://puu.sh/CPvKY/33e9537f7d.png
However it's not a problem running nested, unit tests:
https://puu.sh/CPvLk/a40e8c915c.png

I've created a [sample android project ](https://github.com/gipsey/DavidJUnit5)for demonstration.
@mannodermaus do you have any guess why tests from test report it's not wrapped correctly?
Thanks in advance.

**Comment by mannodermaus** [comment]
The instrumentation test library piggybacks off the [backwards compatibility support of the JUnit Platform](https://junit.org/junit5/docs/current/user-guide/#running-tests-junit-platform-runner), which only supports a subset of the features of JUnit 5. I believe that `@Nested` is not supported by the `JunitPlatform` runner, and because of that, it'll report the tests in a different fashion, compared to the "real" JUnit Jupiter `TestEngine`.

**Comment by gipsey** [comment]
Thanks for the answer.
