### ISSUE TITLE
"jacocoTestReportDebug" task name conflict with gradle-android-junit-jacoco-plugin

### ISSUE THREAD

**Issue by WhosNickDoglio** [mannodermaus/android-junit5#149]
Gradle: 5.2.1
Android Gradle Plugin: 3.3.2
Error: "Cannot add task 'jacocoTestReportDebug' as a task with that name already exists."

Tried adding this plugin to a project already using the [gradle-android-junit-jacoco-plugin](https://github.com/vanniktech/gradle-android-junit-jacoco-plugin) and got the above error message.

[Also created a corresponding issue for the other plugin.](https://github.com/vanniktech/gradle-android-junit-jacoco-plugin/issues/152)

**Comment by mannodermaus** [comment]
Thanks for this. We could simply yield to the existing task if it already exists (through something like `maybeCreate`), but I am not sure of the implications just yet. Another way would be to allow providing a custom name for this.

You should be able to tell android-junit5 to disable Jacoco task generation, so that the ones provided by android-junit-jacoco-plugin are used instead:

```
android.testOptions {
  junitPlatform {
    jacocoOptions.taskGenerationEnabled = false
  }
}
```

That should clear it up.

**Comment by mannodermaus** [comment]
The current `1.4.1.0-SNAPSHOT` has a fix for this, soon to be released in the stable release. When detecting that a Jacoco task with a conflicting name exists, the plugin won't attempt to configure anything JUnit 5-related for it. Note that this might result in incorrect coverage reports for those tests. The plugin will log a warning to console if Jacoco is disabled for any variant.
