### ISSUE TITLE
Cannot apply includePattern filter

### ISSUE THREAD

**Issue by frapontillo** [mannodermaus/android-junit5#171]
Configuring the plugin with `includePattern` as per [documentation](https://github.com/mannodermaus/android-junit5/wiki/Configuration-DSL#per-variant-test-filters) doesn't seem to work, as no tests are ever executed:

```
android {
    testOptions {
        junitPlatform {
            filters {
                includePattern ".*"
            }
        }
    }
}
```

Also, if I try to apply the original snippet in the documentation, Gradle sync won't work as the `$` needs to be escaped. Escaping it still doesn't fix the issue:

```
android.testOptions {
    junitPlatform {
        filters {
            includePattern "^(Test.*|.+[.\$]Test.*|.*Tests?)\$"
        }
    }
}
```

**Comment by mannodermaus** [comment]
Thanks for pointing this out. It seems like the documentation carried over some old configuration settings from the earlier days of JUnit 5 (and this plugin, for that matter). In the old Gradle plugin provided by the JUnit team, you used to be able to specify regular expressions similar to what you linked above. Since moving to the "official" `Test` tasks offered by the Android Gradle Plugin, this was changed to follow [Gradle's `Test#include` API](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.testing.Test.html#org.gradle.api.tasks.testing.Test:include(java.lang.String[])) instead - more specifically, the `String`-based versions of that API. If you specified your filter to match Gradle's expectations of which filters to apply, this should work.

**Comment by mannodermaus** [comment]
I've updated the wiki now to reflect the change in the DSL. Thanks again for bringing this up!
