### ISSUE TITLE
java.lang.AbstractMethodError

### ISSUE THREAD

**Issue by davideas** [mannodermaus/android-junit5#19]
In Android Studio 2.3.3, applying:
```
apply plugin: 'com.android.library'
apply plugin: 'de.mannodermaus.android-junit5'

junitPlatform {
    jupiterVersion "5.0.1"
    platformVersion "1.0.1"
}

dependencies {
    ...
    testCompile junit5()
    testCompile "de.mannodermaus.gradle.plugins:android-junit5-embedded-runtime:1.0.0-RC3-rev1"
}
```
I get this exception:
```
Exception in thread "main" java.lang.AbstractMethodError:
com.intellij.junit5.JUnit5IdeaTestRunner.setStreams(Ljava/lang/Object;Ljava/lang/Object;I)V
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:261)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
```

**Comment by mannodermaus** [comment]
I can reproduce the issue here, and it's tied to the `android-junit5-embedded-runtime` dependency. It seems like overriding the JUnit 5 Runtime causes an incompatibility with the way Android Studio 2.x is hooking into the launch process, most likely due to renamed internal APIs.

You can see that [the method doesn't even exist anymore inside `IdeaTestRunner.java`](https://github.com/JetBrains/intellij-community/blob/master/plugins/junit_rt/src/com/intellij/rt/execution/junit/IdeaTestRunner.java). I guess it would be necessary to override more of the standard JUnit runtime classes to make this work, however that might break other internals of AS (the embedded runtime is a dirty hack as it is already…).

I'm afraid that you are going to need to run your unit tests from Gradle directly (`./gradlew junitPlatformTest` works just fine), at least for the time being, or switch to the AS 3.x Beta.

**Comment by mannodermaus** [comment]
Actually, let me keep this open & experiment a little with including more IntelliJ JARs into the embedded runtime. I'll keep you posted! Might be a few days, though.

**Comment by davideas** [comment]
@mannodermaus, thanks! Currently I can't migrate to AS 3 beta for this [project](https://github.com/davideas/FlexibleAdapter) until AS is in final version. But it will be soon as we know Android team is working hard. So, maybe just try, but don't spend so much time on it. I will stick with _JUnit4_ for a while.

**Comment by davideas** [comment]
@mannodermaus, I tried with AS 3 beta7, but the `embedded-runtime` library is still necessary. However, there works.

**Comment by mannodermaus** [comment]
Yes, even the latest Beta of Android Studio 3 isn't "up-to-date enough" with IntelliJ's master branch to fix the incompatibility issue present in older versions, so the `embedded-runtime` is required there as well. As for Android Studio 2, I haven't managed to replace the `JUnitStarter` responsible for accessing the removed `setStreams` method in the same way, so I'm afraid that launching JUnit 5 tests from the IDE directly isn't going to work with AS 2. I'll update the Readme and attach a notice there. Again, running the Gradle task directly still works, of course.

Thanks for making me aware of this!
