### ISSUE TITLE
System Properties not passed in for instrumentation tests

### ISSUE THREAD

**Issue by ktkopone** [mannodermaus/android-junit5#203]
As far as I can tell this feature should be working in 1.2.0 as per https://github.com/mannodermaus/android-junit5/commit/e50c8a04f865fd07c1935c073cc5f9e567299a88

~~In build.gradle, setting `android.android.testOptions.unitTests.all.systemProperty` will not allow instrumentation tests to access the set value (via System.getProperty in java).~~ Pretty sure I got confused, the takeaway is that setting the below systemProperty only affects unit tests and not instrumentation tests, which would be preferable.

This does work for unit tests, i.e. setting `android.testOptions.unitTests.all.systemProperty 'var', value'` (the unit test equivalent in an android library) does allow unit tests to access the set value via System.getProperty.

Similarly, setting `android.testOptions.junitPlatform.configurationParameter 'var', 'value'` only applies to unit tests and not instrumentation tests.

Environment:
gradle 5.6.4
android library (com.android.library plugin)
android gradle plugin 3.5.2
de.mannodermaus.junit5 1.2.0
junit.jupiter 5.5.2
latest androidx test/annotation dependencies

**Comment by ktkopone** [comment]
Also discovered and tried `testInstrumentationRunnerArgument("systemProperties", "KEY1=value1,KEY2=value2")`, but this doesn't appear to do the trick either.

**Comment by mannodermaus** [comment]
Indeed, the `testOptions.unitTests` DSL applies parameters only to unit tests, not instrumentation tests - no matter if it's JUnit 4 or 5. These are part of an entirely different task structure at the Gradle level, which the plugin does not/cannot intercept. That's why the system properties have to be passed via `testInstrumentationRunnerArgument` in order to work at all. As for the configuration parameters, those have a similar story - the plugin doesn't know a dynamic way to submit these values to Android's instrumentation automatically, since the only API we have is the aforementioned `...RunnerArgument` method.

As for the commits, depends on what you're referring to here. The implementation of JUnit 5 support has seen quite a few iterations ever since its initial inception four years ago, and while its current documentation is supposed to be accurate, past comments may not be so accurate anymore. Could you point me towards the referenced commits that caused the confusion?

**Comment by ktkopone** [comment]
I'm no longer sure what commits I found, but I probably just got confused by the presence of `android` in the testOptions setting. I think this issue can be closed.
