### ISSUE TITLE
RunTests -> No tests for androidTest.apk when running with Flank

### ISSUE THREAD

**Issue by trungung** [mannodermaus/android-junit5#220]
I applied and run succeed in Local phone (connect via adb):
adb shell am instrument -w -m -e runnerBuilder de.mannodermaus.junit5.AndroidJUnit5Builder --no-window-animation  -e debug false -e class 'com.test.demo' dev.test/androidx.test.runner.AndroidJUnitRunner

But alway got the `no tests error` when running with flank tool.
https://github.com/Flank/flank
Flank is a massively parallel Android test runner for Firebase Test Lab.

Did you have any experiencies about this. @mannodermaus Could you please help take a look?

**Comment by mannodermaus** [comment]
Apologies for the late response! 🙇‍♂️

I have no prior experience with Flank, but from a cursory look it seems like its configuration exposes a similar set of configuration parameters to the `firebase` tool that it builds upon. Because of this, I'm inclined to believe that a similar setup should work here. In your `flank.yml` file, you should be able to specify the runner builder for JUnit 5 and the runtime should pick up the tests.

```yml
gcloud:
  # ...
  environment-variables:
    runnerBuilder: de.mannodermaus.junit5.AndroidJUnit5Builder
```

Let me know if you have additional insight here on the Flank version and environment you're trying to get running and I'll see what I can do.
