### ISSUE TITLE
Is Android O still the minimum supported version?

### ISSUE THREAD

**Issue by yschimke** [mannodermaus/android-junit5#228]
Curious whether improved desugaring support means this can go back further?

I'm trying to upgrade instrumentation tests which are primarily used to test older android versions, and I need to upgrade because of a migration to Junit 5.  So kind of between a rock and a hard place.

What happens when tests try to run further back?

**Comment by mannodermaus** [comment]
> What happens when tests try to run further back?

Currently, all JUnit 5 test execution is transparently disabled when running on a device running an OS older than API 26. IIRC this is mostly due to the fact that the internals of JUnit 5 use MethodHandles, which aren't available on older versions of Java. I'm not entirely sure what the new desugaring would do to this, however I believe that third-party libraries would be unaffected by it. In other words, even though the desugaring could rewrite your code's usage of newer Java APIs, it won't touch the binaries of transitive dependencies.

I'm wondering about the necessity to upgrade your instrumentation tests away, though. There shouldn't be anything preventing you from sticking to JU4 for those and only upgrade your unit tests to the newer version.

**Comment by yschimke** [comment]
It's for OkHttp, which is a networking library for the JVM (JDK and Graal native image) and Android platforms.  

Specifically there are multiple competing aims on our project which converge to a very narrow set of workable solutions

- Running tests in JVM (could be Junit 4 or Junit 5)
- Running tests in Graal native images - breaks on some Junit 4 usages - Junit 5 seemed more promising
- Wanting to expand 6-7 integration tests to running out full suite on a device (say the Pixel 4 in your pocket)
- OkHttp is a test framework itself, via mockwebserver module and want to test the modern Junit 5 solution.

For each of these there are different issues, and the most likely solutions tend to be moving forward to the most actively developed new libraries.

This is results from running our existing tests on Android - so it shows this is valuable for us https://github.com/square/okhttp/pull/6424

Closing for now - I've split the problem in two by running the majority of the test suite on Android O+, and a few regression tests on older android versions.

Thanks!

**Comment by mannodermaus** [comment]
Thanks for the context! I've put an item on my list to check the minSdk requirement using the latest toolchain and will let you know if there is any new leeway for it.
