### ISSUE TITLE
Question: Should I use this project?

### ISSUE THREAD

**Issue by macgills** [mannodermaus/android-junit5#236]
Hi, 

I was a maintainer of [Kiwix](https://github.com/kiwix/kiwix-android) for a time and I was able to get junit5 running without this plugin by adding the junit5 dependency and configuring my test tasks to use the junit platform and all unit tests ran as expected. Junit5 was not working in the instrumented tests though. Are there some features I missed or have misconfigured by not using this plugin?

**Comment by mannodermaus** [comment]
Ever since Gradle introduced native support for JUnit 5 a few years ago, the applicable use cases for android-junit5 have been reduced, absolutely. I'm assuming that your setup did not require any Android-specific setup (e.g. distinct test configuration for product flavors), and in that case you should be mostly good with the vanilla JUnit 5. Once you need to configure per-flavor filters, the plugin might help you reduce the boilerplate, however.

As for Android instrumentation tests, the JUnit 5 libraries in this project would help you run the new stuff on eligible phones (i.e. API 26+). As Android's internal instrumentation is based on JUnit 4, our libraries use the compatibility layer to talk to the old world, but still retain most of JUnit 5's benefits (test composition, extension points etc.). You can find more info on those in the wiki!

**Comment by macgills** [comment]
Great, thanks for the explanation! 

I am wondering if it is worth updating the readme to highlight that developers can achieve junit5 testing as I have? I know of some projects that the overhead of adding a new plugin is too great for it to be considered, at least in regulated industries. This project has an important place in the search rankings of "android junit5" and it could be beneficial in spreading the junit5 love.

**Comment by mannodermaus** [comment]
Thanks for the suggestion and apologies for the late reply. Not sure I want to torpedo potential users of my project from using it from the get-go, however I do see value in adding a "Do I need this?" block to the `README.md`. I'll take it into consideration and have derive a doc ticket from this. Thanks again!

**Comment by johnjohndoe** [comment]
Currently, I am migrating my Android application project from JUnit 4 to JUnit 5. I noticed that everything went smooth except for [instrumentation tests](https://github.com/EventFahrplan/EventFahrplan/commit/c76273c1a51a0b6813755fce3db707c568f4d8f7). Once I add your `de.mannodermaus.android-junit5` plugin then I can successfully execute them.

I would be interested to understand what the plugin actually does with regards to the `androidTest` source set. Most of the requirements are already met:

- `testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"`
- `androidTestImplementation "org.junit.jupiter:junit-jupiter-api:5.10.1"`
- `import org.junit.jupiter.api.Test`

I would appreciate if your can enlighten me somewhat. Feel free to put the information into the README or wiki as well.

**Comment by mannodermaus** [comment]
@johnjohndoe In a nutshell, applying the android-junit5 plugin will create the necessary bridge between the instrumentation tests that you write with JUnit Jupiter's API, and the Android instrumentation that executes them. More specifically, we register a `RunnerBuilder` with the JUnit 4-based instrumentation runner provided by Android (i.e. `AndroidJUnitRunner`) so that it can detect tests written against the JUnit Jupiter API at runtime - see [the instrumentation-runner library](https://github.com/mannodermaus/android-junit5/tree/main/instrumentation/runner) for the code. Furthermore, you also get access to a few Android-specific assertion and helper tools when the plugin is applied (i.e. the [instrumentation-core](https://github.com/mannodermaus/android-junit5/tree/main/instrumentation/core) library), but this hook into the registry of the Android instrumentation is the most important point.

**Comment by johnjohndoe** [comment]
@mannodermaus Thank you for explaining the mechanism in details. Very interesting. If Android sticks to JUnit 4 APIs then is it the `junit-vintage-engine` which is used to bridge "their" instrumentation setup into JUnit 5?

Recently, I [migrated to JUnit 5](https://github.com/EventFahrplan/EventFahrplan/commit/023e57ff7c5a13b95843c296906b5e50d14044e1). I only have a few UI-less instrumentation tests. I was surprised that I can omit your plugin and only need `android-test-core`, `android-test-runner` and `testInstrumentationRunnerArgument`. Anything wrong about this approach?

**Comment by johnjohndoe** [comment]
@mannodermaus "anti-vintage engine" makes it very clear to me. Thank you.

I configured my project this way because I did not really understand what the plugin does to the instrumentation test part of my project. All the other unit test run without the plugin. Then I read the [Instrumentation Tests Setup](https://github.com/mannodermaus/android-junit5/wiki/Instrumentation-Tests-Setup) which led to the idea to add the dependencies. Maybe, the page is outdated or I misinterpreted it.

Also, I thought there might be a difference in the setup between instrumentation test without UI and test which involve launching activities/fragments, ...

**Comment by mannodermaus** [comment]
Gotcha, thanks for the insight. At the time of writing that wiki, there was no way for the plugin to set up the instrumentation test pipeline, which is why it still recommends adding everything manually. That should definitely be revisited some day. 😅
