### ISSUE TITLE
Android 12 SDK support

### ISSUE THREAD

**Issue by saschpe** [mannodermaus/android-junit5#256]
When using compileSdk / targetSdk 31 (Android 12), compilation fails in manifest merging due to a service, activity or broadcast receiver that does not have the `exported` XML tag: https://developer.android.com/guide/topics/manifest/activity-element#exported

**Comment by mannodermaus** [comment]
Can you share a bit more about your environment, build files, or a stack trace? What versions of othe plugin and instrumentation are you using? The `core` and `runner` libraries for JUnit 5 support don't define any activities, broadcast receivers nor services so I'd be surprised if this was caused by them.

**Comment by mannodermaus** [comment]
Feel free to comment with some updated info - closing until then
