### ISSUE TITLE
Only "apply plugin: ..." Works

### ISSUE THREAD

**Issue by grndvl1** [mannodermaus/android-junit5#262]
Using the readme only this works for applying the plugin

`apply plugin: 'de.mannodermaus.android-junit5'`

This does not 

`plugins {
    id "de.mannodermaus.android-junit5"
}
`

Not a big deal but all my other plugins can be used in the plugins section with ID  What you do need is the version to make it work.  Not sure why a lot of libraries need the version too.  Must be a setup thing

`id "de.mannodermaus.android-junit5" version "1.8.2.0"`

**Comment by mannodermaus** [comment]
Not sure what you're asking exactly. The plugin version has to be specified _somewhere_, else there would be no way for Gradle to know which artifact to pull. If you want to use the `plugins` DSL, but don't want to set the plugin's version in the `build.gradle` of your app module, the general practice is to specify it in the root-level `build.gradle` with `apply = false`. If your other plugins can be used without their version, it's probably because their versions are set in there, too.

### In `build.gradle`

```groovy
// Plugins are prepared with their full coordinates, including version, here
plugins {
  id 'com.android.application' version '...' apply false
  id 'de.mannodermaus.android-junit5' version '1.8.2.0' apply false
}
```

### In `settings.gradle`

```groovy
// Make sure to configure repositories to pull plugins
pluginManagement {
  repositories {
    gradlePluginPortal()
    google()
    mavenCentral()
  }
}
```

### In `app/build.gradle`

```groovy
// Can omit the version of plugins now, because they are already given by root's build file
plugins {
  id 'com.android.application'
  id 'de.mannodermaus.android-junit5'
}
```

Happy t clarify in case I misunderstood the question. Cheers!
