### ISSUE TITLE
numShards, shardIndex support

### ISSUE THREAD

**Issue by jerry-jeon** [mannodermaus/android-junit5#270]
[The sharding feature that's available in AndroidJunitRunner](https://developer.android.com/training/testing/instrumented-tests/androidx-test-libraries/runner#shard-tests) is not working in AndroidJunit5Runner.
Is there any way to achieve it? I tried to do it through the ExecutionCondition extension, but it makes the test "ignored". I want to make the runner doesn't recognize tests that aren't included in the specific sharding.

I briefly changed the code by refering [the AndroidJunitRunner code](https://android.googlesource.com/platform/frameworks/testing/+/android-support-test/runner/src/main/java/android/support/test/internal/runner/TestRequestBuilder.java#331) and it's working well. But I am not sure it's the right way to do it. 
```kotlin
internal fun createRunnerParams(testClass: Class<*>): AndroidJUnit5RunnerParams {
    val instrumentation = InstrumentationRegistry.getInstrumentation()
    val arguments = InstrumentationRegistry.getArguments()

    // Parse environment variables & pass them to the JVM
    val environmentVariables = arguments.getString(ARG_ENVIRONMENT_VARIABLES)
        ?.run { PropertiesParser.fromString(this) }
        ?: emptyMap()

    // Parse system properties & pass them to the JVM
    val systemProperties = arguments.getString(ARG_SYSTEM_PROPERTIES)
        ?.run { PropertiesParser.fromString(this) }
        ?: emptyMap()

    // Parse configuration parameters
    val configurationParameters = arguments.getString(ARG_CONFIGURATION_PARAMETERS)
        ?.run { PropertiesParser.fromString(this) }
        ?: emptyMap()

    // Parse the selectors to use from what's handed to the runner.
    val selectors = ParsedSelectors.fromBundle(testClass, arguments)

    // The user may apply test filters to their instrumentation tests through the Gradle plugin's DSL,
    // which aren't subject to the filtering imposed through adb.
    // A special resource file may be looked up at runtime, containing
    // the filters to apply by the AndroidJUnit5 runner.
    val filters = mutableListOf<Filter<*>>()
    val contextFilters = GeneratedFilters.fromContext(instrumentation.context)
    filters.addAll(contextFilters)

    class ShardingFilter(val numShards: Int, val shardIndex: Int) : PostDiscoveryFilter {
        override fun apply(descriptor: TestDescriptor): FilterResult {
            if (descriptor.isTest) {
                val remainder = abs(descriptor.hashCode()) % numShards
                val runningShard = remainder == shardIndex
                return if (runningShard) {
                    FilterResult.included(null)
                } else {
                    FilterResult.excluded("excluded")
                }
            }

            for (each in descriptor.children) {
                return if (apply(each).included()) {
                    FilterResult.included(null)
                } else {
                    FilterResult.excluded("excluded")
                }
            }

            return FilterResult.excluded("excluded")
        }
    }

    val numShards = arguments.getString("numShards")?.toInt() ?: -1
    val shardIndex = arguments.getString("shardIndex")?.toInt() ?: -1
    if (numShards > 0 && shardIndex >= 0 && shardIndex < numShards) {
        filters.add(ShardingFilter(numShards, shardIndex))
    }

    return AndroidJUnit5RunnerParams(
        selectors,
        filters,
        environmentVariables,
        systemProperties,
        configurationParameters
    )
}
```

**Comment by jkj8790** [comment]
Hello @mannodermaus . Thanks for working on it.
It’s working well, but there’s a problem related to the test result.

I have tests both of junit4 and junit5. For the shard that only contains junit4 tests, the test result considered as failed even if all tests are passed. (As you can see the screen shot) ![Screen Shot 2022-07-08 at 4 07 01 PM](https://user-images.githubusercontent.com/5154440/177944681-fddbfc73-adcd-4b34-9a0b-13f204340321.png)
When it happens the suspicious log appears - `I/TestRunner: finished: JUnit Jupiter`  If the shard contains at least one junit5 test, it doesn’t appear.
![Screen Shot 2022-07-08 at 4 10 06 PM](https://user-images.githubusercontent.com/5154440/177944687-8595ad23-318e-4e6d-883d-59fdfd904fd6.png)

Here's the part of XML file that exported from the result. Each tests are passed but in the testSuite tag, the result is failed. I guess it’s why the result shown as failed in the android studio.
<img width="1787" alt="Screen Shot 2022-07-08 at 4 54 36 PM" src="https://user-images.githubusercontent.com/5154440/177945022-67f95d56-068d-47c0-b459-16e37d2083c7.png">

I created [the sample project](https://github.com/jkj8790/temp-android-junit5test) that can reproduce the issue. In the project problematic numShards and shardIndex value is assigned already, so if you run the whole tests then you will see the issue.

Because of it, my project always fails on the Firebase Testlab. I would really appreciate it if you could help me. 
If you need more information, please let me know. 
Thank you.

**Comment by mannodermaus** [comment]
Hey, apologies for only coming back to this now. Thank you for the sample project! I executed the instrumentation tests in it and it ran the same tests I can see in your screenshots, but my XML file has a different format with less information. I wonder if there have been changes to AS itself that resolved an internal issue here? (For context, I'm running from AS Iguana Canary 3)

<img width="1429" alt="Screenshot 2023-09-18 at 10 45 44" src="https://github.com/mannodermaus/android-junit5/assets/3897705/210d2f20-8a8c-4026-9f9b-d52f50cfddf5">
