### ISSUE TITLE
Add support for Gradle Plugins DSL

### ISSUE THREAD

**Issue by igorwojda** [mannodermaus/android-junit5#283]
Moderns plugins are configured without a need of adding `classpath` (legacy config). They are added by usage of [plugins DSL](https://docs.gradle.org/current/userguide/plugins.html#sec:plugins_block) and they are retrieved from [Gradle plusings repo](https://plugins.gradle.org/) eg. https://plugins.gradle.org/plugin/uk.co.iotatech.gradle.detekt

It would be nice to have this in the `android-junit5` plugin.

**Comment by mannodermaus** [comment]
We do have this in the plugin, actually! Since a few versions ago, there's nothing stopping you from adding `id("de.mannodermaus.android-junit5").version("1.8.2.1")` to your build script and skip the `classpath` declaration. I do agree that the README could be clearer about this, however. I'll make sure to advertise this possibility in there shortly.

**Comment by igorwojda** [comment]
[Works as expected](https://github.com/igorwojda/android-showcase/commit/6c777344a9c27f78b2de85a731a81e6f6a26696a). THX
