### ISSUE TITLE
Clarification with regards to JaCoCo

### ISSUE THREAD

**Issue by johnjohndoe** [mannodermaus/android-junit5#289]
# Context
- I am trying to setup test coverage reports with JaCoCo for an Android application project which has several Android library and Java library modules.
- I am trying to use https://github.com/vanniktech/gradle-android-junit-jacoco-plugin.
- I noticed log output such as `[android-junit5]: Jacoco task for variant 'devDebug' already exists. Disabling customization for JUnit 5..`

# JaCoCo clarification
- There are [multiple mentions](https://github.com/mannodermaus/android-junit5/search?q=jacoco&type=issues) of "JaCoCo" in this repository.
- I cannot find any dependency to JaCoCo.

  ``` python
  +--- de.mannodermaus.gradle.plugins:android-junit5:1.8.2.1
  |    +--- org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.31 (*)
  |    +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.31 (*)
  |    +--- com.github.zafarkhaja:java-semver:0.9.0
  |    \--- org.junit.platform:junit-platform-commons:1.8.2
  |         \--- org.junit:junit-bom:5.8.2
  |              \--- org.junit.platform:junit-platform-commons:1.8.2 (c)
  ```

- I cannot find any "JaCoCo" tasks being added by your plugin.
- Can you please clarify here (and probably in the docs) to what extend JaCoCo is leveraged or if any interference with JaCoCo or such plugins is known?

**Comment by mannodermaus** [comment]
Apologies for the late reply! The JUnit 5 plugin for Android will only activate its Jacoco integration when the target project explicitly enables Jacoco itself (via `apply plugin: "jacoco"`). There is no need for a third-party dependency since Jacoco is baked into the Gradle APIs itself. The reason for the integration is to submit test coverage metrics from JUnit 5 tests to Jacoco, which would otherwise miss it.

There were some interferences in the past, which led to the eventual "auto-disabling" message that you mentioned above. Essentially, the JUnit 5 plugin assumes that if there already are Jacoco tasks for each variant, the user knows best how to configure them and will back off trying to do it for them.

**Comment by johnjohndoe** [comment]
Thank you for the clarification. I will give it another try.
