### ISSUE TITLE
Is it possible to run junit5 tests with robolectric?

### ISSUE THREAD

**Issue by illuzor** [mannodermaus/android-junit5#305]
I see that RobolectricTestRunner is based in junit4 runner and i have initialization error
![image](https://github.com/mannodermaus/android-junit5/assets/1530314/741ea6dd-bb99-4eae-a1ed-12da9b9b8c32)

**Comment by mannodermaus** [comment]
The short answer is no. The way Robolectric injects the modified version of the `android.jar` file for tests depends heavily on custom class loading via their custom `Runner`, which cannot be used from JUnit 5 (in other words, you can't mix Jupiter's `@Test` with JUnit 4's `@RunWith`).

That being said, a recent version upgrade of JUnit 5 has introduced the ability for custom class loading. If you want to dive into the lengthy discussion, the ticket is [here](https://github.com/junit-team/junit5/issues/201). With this merged, it's theoretically possible to port over Robolectric's old code to a JUnit 5 extension – the main problem is, nobody was able to dedicate time to it just yet.

The Robolectric feature ticket to support JUnit 5 is [here](https://github.com/robolectric/robolectric/issues/3477) and I'm crossing my fingers that we will see a Robolectric extension in the future! Until then, please stick to `@org.junit.Test` for your Robolectric tests. 🙇‍♂️

(I'm going to pin this issue for visibility since this question does come up every once in a while. Hope you don't mind!)

**Comment by emartynov** [comment]
People, is it possible to run Robolectric with vintage engine?

**Comment by mannodermaus** [comment]
@emartynov It is! If you annotate your Robolectric tests with the JUnit 4 annotations (i.e. `@org.junit.Test` and friends) and run them through the vintage engine, it'll work just fine. This is why I generally recommend people to prefer JUnit 5, write as many tests as possible with that API, and only resort to JUnit 4 for tests that do require Robolectric and its custom runner.

**Comment by mannodermaus** [comment]
Some new developments are spinning up in this space!

First, @warnyul the absolute GOAT has started publicizing [an interop plugin to bridge the gap between Robolectric and JUnit 5](https://github.com/apter-tech/junit5-robolectric-extension). Essentially, it **is** possible to run those tests on the JUnit Platform now! YMMV, but my first impression is very good. Show him some love by starring it!

Second, [Robolectric is participating in Google Summer of Code 2024](https://robolectric.org/blog/2024/02/25/robolectric-2024-gsoc/). One of the suggested projects in their pitch deck deals with the refactoring of Robolectric to support JUnit 5! Of course, this is a much more long-term undertaking, but I'm delighted to see that they are starting to throw the idea of evolution out there. 😊
