### ISSUE TITLE
Test filtering via commandline does not work

### ISSUE THREAD

**Issue by jaredsburrows** [mannodermaus/android-junit5#31]
`gradlew testDebug --tests="*ClassName*"`

See https://github.com/jaredsburrows/android-gif-example/pull/37

**Comment by mannodermaus** [comment]
Good catch! Neither does it work with the main JUnit 5 Gradle plugin, though. For that reason, I might want to move the conceptualization of how to pass the complex structure of selectors & filters via command line to the junit5-core team first.

For now, you'd have to configure the selectors directly via the plugin in your `build.gradle`:

```groovy
junitPlatform {
  filters {
    includeClassNamePattern "*ClassName*"
  }
}
```

**Comment by mannodermaus** [comment]
For future reference, I'm also linking to the official [Gradle issue](https://github.com/gradle/gradle/issues/1037#issuecomment-336961104) relating to JUnit 5 Design Specs, in which the same request has been laid out.

**Comment by jaredsburrows** [comment]
Thank you.

**Comment by mannodermaus** [comment]
Quick update: By now, lots of things have changed compared to when this issue was raised. We now utilize the first-party support of JUnit 5 within Gradle for this plugin, so it's now possible to leverage the Gradle options for test filtering, as described in the OP.

Furthermore, if you want to have slightly more static configuration of filters, you can use the per-variant filters DSL - more info [on the wiki](https://github.com/mannodermaus/android-junit5/wiki/Configuration-DSL-(Kotlin)#per-variant-test-filters).
