### ISSUE TITLE
Test run failed to complete. Expected 9 tests, received 4

### ISSUE THREAD

**Issue by bddckr** [mannodermaus/android-junit5#344]
Since updating from the last snapshot versions of both the plugin and the instrumentation library to the latest release, I'm getting this issue:

> &gt; Task :my:project:gradleManagedDeviceApiLevel31DebugAndroidTest
Test run failed to complete. Expected 9 tests, received 4

All the affected projects use annotations to conditionally enable/disable tests. One such test uses `@EnabledOnSdkVersion`, but I also have some custom annotations in use.

```kotlin
@ParameterizedTest
@MethodSource("getAllStreamTypes")
@EnabledOnSdkVersion(from = Build.VERSION_CODES.P)
```

The issue only occurs to instrumentation tests. Local tests are fine. This was _not_ happening on the snapshot versions.

While the task name above shows that I'm executing the instrumentation tests with a [Gradle Managed Device](https://developer.android.com/studio/test/gradle-managed-devices), this reproduces when running the tests from Android Studio as well.

| Component                   | Version  |
|-----------------------------|----------|
| Plugin                      | 1.10.2.0 |
| Instrumentation<br>(via `instrumentationTests.includeExtensions.set(true)`)            | 1.5.0    |
| AGP (Android Gradle Plugin) | 8.5.1    |
| Gradle                      | 8.9      |
| `org.junit:junit-bom`       | 5.10.3   |

**Comment by mannodermaus** [comment]
Thanks for reporting. I'm surprised that you're still seeing this with the latest, since there has been [some](https://github.com/mannodermaus/android-junit5/pull/326) [prior](https://github.com/mannodermaus/android-junit5/issues/298) [work](https://github.com/mannodermaus/android-junit5/issues/316) to this extent. In fact, I'm unable to make this work with conditional test annotations in the sample project.

Would it be possible for you to share a bit more about these 9 tests that make up this suite? If it's not an open source repo, you can redact method bodies and class/method names, of course. But I'd like to get some more context about what the test sources need to look like to still trigger this. Furthermore, you are referring to "custom annotations"; what do these do and can you confirm that the issue persists even when you remove them from the equation?

**Comment by bddckr** [comment]
I'm slowly building up my private project from the sample in this repo, but also trying to slowly build down my project to match the sample more.

So far I can't reproduce the issue in the sample. But I can see that my custom annotation isn't the issue in my project - that project reproduces the issue when only using `@EnabledOnSdkVersion`.

I'm digging further into it and will report back!

**Comment by bddckr** [comment]
Got it!

[Plugin 1.10.2.0](https://github.com/mannodermaus/android-junit5/releases/tag/plugin-1.10.2.0) actually ships with `Libraries.instrumentationVersion` set to `"1.4.0"`.

When manually specifying the version, I have no issue anymore:
```kotlin
instrumentationTests {
    version.set("1.5.0")
    includeExtensions.set(true)
}
```

That makes sense to me. Should have noticed that right away 😅 

Feel free to close this issue if that's intended. But perhaps it's unexpected for the latest plugin release to not use the latest instrumentation libraries?

**Comment by bddckr** [comment]
I'm gonna close this. I can see that the version referenced by the plugin was changed [_after_ the plugin was released](https://github.com/mannodermaus/android-junit5/commit/eb576a028111100044fbca3069caa7dce6e33644#diff-3d59e3f2588d14f539972022d4567e0f846c31f15db274d7c980be3d2b61fb1d). I was just _assuming_ the plugin would reference the latest instrumentation library, because GitHub's release page makes it look like that was the release order. (But now checking the timestamps I can see that the order is opposite of what GitHub shows 😆 🤷 )

**Comment by mannodermaus** [comment]
Oh, great catch 👀 That is definitely a mistake, and 1.10.2.0 should roll with 1.5.0. Sorry about that! Let me track this in a follow-up ticket.
