### ISSUE TITLE
Running tests on multiple flavors

### ISSUE THREAD

**Issue by Rosomack** [mannodermaus/android-junit5#36]
When I run tests on 3 different app flavors, the test outputs all land under `app/build/test-results/junit-platform/TEST-junit-vintage.xml`. This effectively means that if I want to get test results for 3 different flavors independently I can't because they overwrite each other.

I would expect them to land under separate folders like
`app/build/test-results/vanillaDebug/junit-platform/TEST-junit-vintage.xml`
`app/build/test-results/chocolateDebug/junit-platform/TEST-junit-vintage.xml`
`app/build/test-results/pistachioDebug/junit-platform/TEST-junit-vintage.xml`

**Comment by mannodermaus** [comment]
Sounds reasonable - [this variant-unaware statement is the culprit here](https://github.com/mannodermaus/android-junit5/blob/7d8a6698053b3902e2c8c43e90f33a9bae102fee/android-junit5/src/main/kotlin/de/mannodermaus/gradle/plugins/junit5/tasks/UnitTest.kt#L193).

I'll prepare a unit test that exposes this bug, then schedule its fix for the next release. Thanks for reporting!

**Comment by Rosomack** [comment]
Thanks for the hard work!

**Comment by mannodermaus** [comment]
This will be included in the upcoming `1.0.22` release of the plugin. If you need the fix right now, consider using the latest `-SNAPSHOT` version instead!

**Comment by mannodermaus** [comment]
FYI, this has been released in `1.0.22`!
