### ISSUE TITLE
No code coverage generated

### ISSUE THREAD

**Issue by erik-browne-emc** [mannodermaus/android-junit5#4]
Running the junitPlatformTest task doesn't generate an EXEC code coverage file.

Example of someone getting JaCoCo code coverage working with JUnit 5: http://stackoverflow.com/questions/39362955/gradle-jacoco-and-junit5

**Comment by aurae** [comment]
This is being discussed for the Java-based Gradle plugin [over at junit-team/junit5](https://github.com/junit-team/junit5/issues/1024). If they decide to go for this enhancement, I'll definitely make sure to extend the Jacoco support for our variant-based needs!

**Comment by alixwar** [comment]
Meanwhile is there any workaround for this? The one for the Java plugin does not work for me:

* Where:
Build file 'D:\Git\cliq-pd-app\application\build.gradle' line: 207

```
* What went wrong:
A problem occurred configuring project ':application'.
> Could not get unknown property 'junitPlatformTest' for object of type org.gradle.testing.jacoco.plugins.JacocoPluginExtension.
```

**Comment by aurae** [comment]
I have invested some time in the integration of JaCoCo inside the JUnit 5 plugin myself now, since the topic seems to have been added to the backlog of the junit5 project. It's only available in the latest SNAPSHOT release as of now, so it's also not documented in the README, but here's the gist:

* If you don't have it already, add the snapshot repository: `maven { url "https://oss.sonatype.org/content/repositories/snapshots" }`
* Update your plugin dependency to version `1.0.0.1-SNAPSHOT`
* Apply the `jacoco` plugin to your module
* Optionally configure what reports should be generated by JaCoCo using the boolean `junitPlatform.jacoco.***Report` fields (where *** can be `csv`, `xml` or `html`)
* Run code coverage tests using the per-variant `jacocoTestReport***` tasks, or use the catch-all variant `jacocoTestReport` itself

I don't have much experience with JaCoCo myself, but I do get reports generated for the projects that I've tested this new snapshot in. Please let me know if there's anything wrong or missing with this approach! I'm also pinging @alixwar who was asking about this as well.

**Comment by alixwar** [comment]
Thanks for helping out with this @aurae 
I've actually made it work (with the work-around) but not in combination with Robolectric at the moment. 
I can post my code (relevant parts) here if requested.

**Comment by alixwar** [comment]
An update: I verified the content of the exec file and it seems it's all in there, even the Robolectric tests.

**Comment by benwicks** [comment]
@aurae which plugin are you referring to when you said the following?
```
Update your plugin dependency to version 1.0.0.1-SNAPSHOT
```

**Comment by aurae** [comment]
`de.mannodermaus.gradle.plugins:android-junit5:1.0.0.1-SNAPSHOT`

**Comment by alixwar** [comment]
A question has been asked [here](https://github.com/junit-team/junit5/issues/1024 ) if the Android plugin does something special. Maybe we can try to solve the last piece of the puzzle together to at least get a work-around until there is an official integration?

**Comment by alixwar** [comment]
Sorry for the late feedback but I've now tried 1.0.0.1-SNAPSHOT. I was forced to remove the workaround mentioned earlier `(applyTo...)` since otherwise there would be collisions of using the keyword jacoco.
So I removed the workarounds and run `gradlew clean jacocoTestReportDebug`

The good thing: I now get coverage for both "vanilla" JUnit4 tests and JUnit5 tests
Bad thing: Unit tests with runner "RobolectricTestRunner" still gives no code coverage. But I guess this is out-of-scope for this project. 

Thank you very much @mannodermaus !

**Comment by alixwar** [comment]
If anyone is interested I added a sample project using Robolectric. I'm not getting any code coverage for the test that I added in the sample: https://github.com/mannodermaus/android-junit5/pull/18

**Comment by mannodermaus** [comment]
I have released the first official version of the plugin with JaCoCo integration as `1.0.10`. You can now migrate away from the SNAPSHOT!

**Comment by sureshjoshi** [comment]
Regarding this issue - I still can't seem to get any code coverage metrics (using the Jacoco plugin or vanilla Android Studio). 

I get a report that tells me I have 0 coverage, with a suite that I know is close to 80% coverage. 

Could there be anything missing other than:
```
apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'de.mannodermaus.android-junit5'
apply plugin: 'jacoco'

...

testImplementation junit5()
testImplementation junit5Params() // Parameterized tests
testCompileOnly junit5EmbeddedRuntime() // AS3 workaround
testImplementation 'org.assertj:assertj-core:3.8.0'
```

The actual JUnit5 unit tests run great (using AssertJ)

**Comment by mannodermaus** [comment]
You can inspect the assembled Code Coverage tasks by adding `--info` to your Gradle invocation, then filter through the output to find the plugin's log statements (they are all prefixed with `[android-junit5]`). For each Jacoco task created by the plugin, the Execution Data, Source & Class Directories are logged. Maybe there's a discrepancy somewhere and the plugin doesn't figure out your project's structure correctly?

**Comment by sureshjoshi** [comment]
Actually, this may be a problem with AS3.0 and Kotlin

https://issuetracker.google.com/issues/64929213
