### ISSUE TITLE
Tests not executed

### ISSUE THREAD

**Issue by slott** [mannodermaus/android-junit5#95]
After adding this none of my old vintage tests are executed when executing the test target from the command line.  Ie running "./gradlew app:testWorldDebug" just returns 

BUILD SUCCESSFUL in 2s
203 actionable tasks: 1 executed, 202 up-to-date

And thats it.

Any ideas as to what I might have done wrong ?

**Comment by mannodermaus** [comment]
I have a couple of questions about your setup. Does this also happen when you perform a clean build? Is the `:testWorldDebug` one of the tasks that is marked `UP-TO-DATE`? Just in case, can you try running the generated JUnit 5 task and check if that helps (with your variant, this should be called `junitPlatformTestWorldDebug`)? How did you configure your build file? By default, the JUnit 4-based tasks are disabled when you apply the android-junit5 plugin, because the Vintage engine takes care of running those.

**Comment by mannodermaus** [comment]
Feel free to reopen if you're still having trouble.
