### ISSUE TITLE
JUnit 5 Support For Android SDKs Below 26

### ISSUE THREAD

**Issue by jdannhausenbrun** [mannodermaus/android-junit5#98]
I'm working on a project that requires running JUnit5 tests on phones with sdks below 26.  Is it possible to get support for sdks below 26?  The suggested fix of using tools:overrideLibrary="de.mannodermaus.junit5" to force usage did not function to solve the issue.

The specific error message is below:
Suggestion: use a compatible library with a minSdk of at most 15,
        or increase this project's minSdk version to at least 26,
        or use tools:overrideLibrary="de.mannodermaus.junit5" to force usage (may lead to runtime failures)

**Comment by mannodermaus** [comment]
Instrumentation tests written with Jupiter don't and won't run on devices below API level 26, because JUnit 5 uses Java 8-specific APIs that didn't exist on Android before the Oreo release. If you want to play with the new APIs on supported devices, use a dedicated branch in your VCS, or only add the JUnit 5 to a special product flavor.

**Comment by matejdro** [comment]
Creating separate product flavor is a hassle, you need to manage it along other build flavors and it also doubles your compile time (since instrumented test flavor would compile separately than your main flavor).

What I did:

1. Put another `AndroidManifet.xml` into `src\androidTest` folder:

```xml
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:tools="http://schemas.android.com/tools"
    package="com.example.myapp">

    <uses-sdk tools:overrideLibrary="de.mannodermaus.junit5" />

</manifest>
```

2. Make sure you have java source and target set to `1.8` in gradle files (README of this project has this already in)

Then you can compile it normally regardless of your minSdk. However it still does not run on SDK < 26.

**Comment by mannodermaus** [comment]
This is a great approach, @matejdro! An older device wouldn't run tests written against the Jupiter API, but should still execute JUnit 4 as usual. I'll validate this, though - it's possible that the JUnit 5 integration needs to do an explicit version check, or else it could crash the Jupiter `TestEngine` at runtime.

**Comment by jemshit** [comment]
I missed this line, **Put another AndroidManifet.xml into src\androidTest folder**, so highlighting it
